LOG_DIR=log
LOG_FILE=logs.log
BOOKS_URL=http://localhost:8080/LibraryServer/api/books/
USERS_URL=http://localhost:8080/LibraryServer/api/users/
MULTICAST_ADD=230.0.0.1
USERS_PORT=20000
DISCOVER_ALL_USERS=GET_ALL_USERS
DISCOVER_USER=DISCOVER_USER
HOST=localhost
DISCOVERY_SERVER_TCP_PORT=8888
END_MSG=END
CHAT_MESSAGE=CHAT_MESSAGE
KEY_STORE_PATH=keystore.jks
KEY_STORE_PASSWORD=password123
OK=OK
GROUP_MESSAGE=GROUP_MESSAGE